variables:
  AUDIT_AGENT_PROFILES_LIST:
      required: false
      type: array
      default:
        - linux-cis
        - linux-benchmark

  AUDIT_AGENT_RULES_LIST:
      required: false
      type: array
      default:
        - echo-hello
        - env-user-password
